#if !canImport(ObjectiveC)
import XCTest

extension BasicTypesTestsFromXML {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BasicTypesTestsFromXML = [
        ("testMappingAnyObjectArrayFromXML", testMappingAnyObjectArrayFromXML),
        ("testMappingAnyObjectDictionaryFromXML", testMappingAnyObjectDictionaryFromXML),
        ("testMappingAnyObjectFromXML", testMappingAnyObjectFromXML),
        ("testMappingBoolArrayFromXML", testMappingBoolArrayFromXML),
        ("testMappingBoolDictionaryFromXML", testMappingBoolDictionaryFromXML),
        ("testMappingBoolFromXML", testMappingBoolFromXML),
        ("testMappingDoubleArrayFromXML", testMappingDoubleArrayFromXML),
        ("testMappingDoubleDictionaryFromXML", testMappingDoubleDictionaryFromXML),
        ("testMappingDoubleEnumFromXML", testMappingDoubleEnumFromXML),
        ("testMappingDoubleFromXML", testMappingDoubleFromXML),
        ("testMappingEnumIntArrayFromXML", testMappingEnumIntArrayFromXML),
        ("testMappingEnumIntArrayFromXMLShouldNotCrashWithNonDefinedValue", testMappingEnumIntArrayFromXMLShouldNotCrashWithNonDefinedValue),
        ("testMappingEnumIntDictionaryFromXML", testMappingEnumIntDictionaryFromXML),
        ("testMappingEnumIntDictionaryFromXMLShouldNotCrashWithNonDefinedValue", testMappingEnumIntDictionaryFromXMLShouldNotCrashWithNonDefinedValue),
        ("testMappingFloatArrayFromXML", testMappingFloatArrayFromXML),
        ("testMappingFloatDictionaryFromXML", testMappingFloatDictionaryFromXML),
        ("testMappingFloatEnumFromXML", testMappingFloatEnumFromXML),
        ("testMappingFloatFromXML", testMappingFloatFromXML),
        ("testMappingIntArrayFromXML", testMappingIntArrayFromXML),
        ("testMappingIntDictionaryFromXML", testMappingIntDictionaryFromXML),
        ("testMappingIntegerFromXML", testMappingIntegerFromXML),
        ("testMappingIntegerWithOverflowFromXML", testMappingIntegerWithOverflowFromXML),
        ("testMappingIntEnumFromXML", testMappingIntEnumFromXML),
        ("testMappingIntEnumFromXMLShouldNotCrashWithNonDefinedvalue", testMappingIntEnumFromXMLShouldNotCrashWithNonDefinedvalue),
        ("testMappingStringArrayFromXML", testMappingStringArrayFromXML),
        ("testMappingStringDictionaryFromXML", testMappingStringDictionaryFromXML),
        ("testMappingStringEnumFromXML", testMappingStringEnumFromXML),
        ("testMappingStringEnumFromXMLShouldNotCrashWithNonDefinedValue", testMappingStringEnumFromXMLShouldNotCrashWithNonDefinedValue),
        ("testMappingStringFromNSStringXML", testMappingStringFromNSStringXML),
        ("testMappingStringFromXML", testMappingStringFromXML),
        ("testObjectModelOptionalDictionnaryOfPrimitives", testObjectModelOptionalDictionnaryOfPrimitives),
    ]
}

extension BasicTypesTestsToXML {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BasicTypesTestsToXML = [
        ("testMappingAnyObjectArrayToXML", testMappingAnyObjectArrayToXML),
        ("testMappingAnyObjectDictionaryToXML", testMappingAnyObjectDictionaryToXML),
        ("testMappingAnyObjectToXML", testMappingAnyObjectToXML),
        ("testMappingBoolArrayToXML", testMappingBoolArrayToXML),
        ("testMappingBoolDictionaryToXML", testMappingBoolDictionaryToXML),
        ("testMappingBoolToXML", testMappingBoolToXML),
        ("testMappingDoubleArrayToXML", testMappingDoubleArrayToXML),
        ("testMappingDoubleDictionaryToXML", testMappingDoubleDictionaryToXML),
        ("testMappingDoubleEnumToXML", testMappingDoubleEnumToXML),
        ("testMappingDoubleToXML", testMappingDoubleToXML),
        ("testMappingEnumIntArrayToXML", testMappingEnumIntArrayToXML),
        ("testMappingEnumIntDictionaryToXML", testMappingEnumIntDictionaryToXML),
        ("testMappingFloatArrayToXML", testMappingFloatArrayToXML),
        ("testMappingFloatDictionaryToXML", testMappingFloatDictionaryToXML),
        ("testMappingFloatEnumToXML", testMappingFloatEnumToXML),
        ("testMappingFloatToXML", testMappingFloatToXML),
        ("testMappingIntArrayToXML", testMappingIntArrayToXML),
        ("testMappingIntDictionaryToXML", testMappingIntDictionaryToXML),
        ("testMappingIntegerToXML", testMappingIntegerToXML),
        ("testMappingIntEnumToXML", testMappingIntEnumToXML),
        ("testMappingStringArrayToXML", testMappingStringArrayToXML),
        ("testMappingStringDictionaryToXML", testMappingStringDictionaryToXML),
        ("testMappingStringEnumToXML", testMappingStringEnumToXML),
        ("testMappingStringToXML", testMappingStringToXML),
        ("testObjectToModelDictionnaryOfPrimitives", testObjectToModelDictionnaryOfPrimitives),
    ]
}

extension GenericObjectsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GenericObjectsTests = [
        ("testGenericSubclass", testGenericSubclass),
        ("testMappingAGenericObject", testMappingAGenericObject),
        ("testMappingAGenericObjectViaMappableExtension", testMappingAGenericObjectViaMappableExtension),
        ("testSubclass", testSubclass),
        ("testSubclassWithGenericArrayInSuperclass", testSubclassWithGenericArrayInSuperclass),
    ]
}

extension XMLCustomTransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLCustomTransformTests = [
        ("testCustomFormatDateTransform", testCustomFormatDateTransform),
        ("testDateTransform", testDateTransform),
        ("testEnumTransform", testEnumTransform),
        ("testHexColorTransform", testHexColorTransform),
        ("testInt64MaxValue", testInt64MaxValue),
        ("testIntToStringTransformOf", testIntToStringTransformOf),
        ("testURLTranform", testURLTranform),
    ]
}

extension XMLDataTransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLDataTransformTests = [
        ("testXMLDataTransform", testXMLDataTransform),
    ]
}

extension XMLDictionaryTransformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLDictionaryTransformTests = [
        ("testDictionaryTransform", testDictionaryTransform),
    ]
}

extension XMLMappableExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLMappableExtensionsTests = [
        ("testArrayFromString", testArrayFromString),
        ("testArrayToXMLAndBack", testArrayToXMLAndBack),
        ("testInitFromString", testInitFromString),
        ("testSetFromString", testSetFromString),
        ("testSetInitFailsWithEmptyString", testSetInitFailsWithEmptyString),
        ("testSetToXMLAndBack", testSetToXMLAndBack),
        ("testToXMLAndBack", testToXMLAndBack),
    ]
}

extension XMLMappableTypesWithTransformsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLMappableTypesWithTransformsTests = [
        ("testParsing2DimensionalArrayOfObjectsWithTransform", testParsing2DimensionalArrayOfObjectsWithTransform),
        ("testParsingArrayOfObjectsWithTransform", testParsingArrayOfObjectsWithTransform),
        ("testParsingDictionaryOfArrayOfObjectsWithTransform", testParsingDictionaryOfArrayOfObjectsWithTransform),
        ("testParsingDictionaryOfObjectsWithTransform", testParsingDictionaryOfObjectsWithTransform),
        ("testParsingImplicitlyUnwrapped2DimensionalArrayOfObjectsWithTransform", testParsingImplicitlyUnwrapped2DimensionalArrayOfObjectsWithTransform),
        ("testParsingImplicitlyUnwrappedArrayOfObjectsWithTransform", testParsingImplicitlyUnwrappedArrayOfObjectsWithTransform),
        ("testParsingImplicitlyUnwrappedDictionaryOfArrayOfObjectsWithTransform", testParsingImplicitlyUnwrappedDictionaryOfArrayOfObjectsWithTransform),
        ("testParsingImplicitlyUnwrappedDictionaryOfObjectsWithTransform", testParsingImplicitlyUnwrappedDictionaryOfObjectsWithTransform),
        ("testParsingImplicitlyUnwrappedSetOfObjectsWithTransform", testParsingImplicitlyUnwrappedSetOfObjectsWithTransform),
        ("testParsingImplicitlyUnwrappedSingleInstanceWithTransform", testParsingImplicitlyUnwrappedSingleInstanceWithTransform),
        ("testParsingOptional2DimensionalArrayOfObjectsWithTransform", testParsingOptional2DimensionalArrayOfObjectsWithTransform),
        ("testParsingOptionalArrayOfObjectsWithTransform", testParsingOptionalArrayOfObjectsWithTransform),
        ("testParsingOptionalDictionaryOfArrayOfObjectsWithTransform", testParsingOptionalDictionaryOfArrayOfObjectsWithTransform),
        ("testParsingOptionalDictionaryOfObjectsWithTransform", testParsingOptionalDictionaryOfObjectsWithTransform),
        ("testParsingOptionalSetOfObjectsWithTransform", testParsingOptionalSetOfObjectsWithTransform),
        ("testParsingOptionalSingleInstanceWithTransform", testParsingOptionalSingleInstanceWithTransform),
        ("testParsingSetOfObjectsWithTransform", testParsingSetOfObjectsWithTransform),
        ("testParsingSingleInstanceWithTransform", testParsingSingleInstanceWithTransform),
    ]
}

extension XMLMapperTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XMLMapperTests = [
        ("testArrayOfCustomObjects", testArrayOfCustomObjects),
        ("testArrayOfEnumObjects", testArrayOfEnumObjects),
        ("testBasicParsing", testBasicParsing),
        ("testDictionaryOfArrayOfCustomObjects", testDictionaryOfArrayOfCustomObjects),
        ("testDictionaryOfCustomObjects", testDictionaryOfCustomObjects),
        ("testDictionaryParsing", testDictionaryParsing),
        ("testDictionryOfEnumObjects", testDictionryOfEnumObjects),
        ("testDoubleParsing", testDoubleParsing),
        ("testInstanceParsing", testInstanceParsing),
        ("testInvalidXMLResultsInNilObject", testInvalidXMLResultsInNilObject),
        ("testMapArrayXML", testMapArrayXML),
        ("testMapArrayXMLWithNoArray", testMapArrayXMLWithNoArray),
        ("testNullObject", testNullObject),
        ("testOptionalStringParsing", testOptionalStringParsing),
        ("testShouldPreventOverwritingMappableProperty", testShouldPreventOverwritingMappableProperty),
        ("testToXMLAndBack", testToXMLAndBack),
        ("testToXMLArray", testToXMLArray),
        ("testToXMLArrayAndBack", testToXMLArrayAndBack),
        ("testUnknownPropertiesIgnored", testUnknownPropertiesIgnored),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BasicTypesTestsFromXML.__allTests__BasicTypesTestsFromXML),
        testCase(BasicTypesTestsToXML.__allTests__BasicTypesTestsToXML),
        testCase(GenericObjectsTests.__allTests__GenericObjectsTests),
        testCase(XMLCustomTransformTests.__allTests__XMLCustomTransformTests),
        testCase(XMLDataTransformTests.__allTests__XMLDataTransformTests),
        testCase(XMLDictionaryTransformTests.__allTests__XMLDictionaryTransformTests),
        testCase(XMLMappableExtensionsTests.__allTests__XMLMappableExtensionsTests),
        testCase(XMLMappableTypesWithTransformsTests.__allTests__XMLMappableTypesWithTransformsTests),
        testCase(XMLMapperTests.__allTests__XMLMapperTests),
    ]
}
#endif
